name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: Coordinate-Cat/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.6d71f63c8038e95dee360a341aea3263c88c225a }}
          GIST_ID: d4907de718adc8f750737e587fb976e0
          WAKATIME_API_KEY: ${{ secrets.6a5fe232-d016-4f70-ab8b-619d37c71eb7 }}
